# Generated by Django 2.1.7 on 2019-03-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_auto_20190310_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyect',
            name='titular',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
